### ISSUE TITLE
Create New Department Button 

### ISSUE THREAD

**Issue by garrett-vangilder** [TeamCharles/workforce-management#24]
### Feature Description

This button will be located on the department listing page. When you click the button it should route the user to different view. 

### Recommended Actions
>Refer to the [project requirements](https://github.com/nashville-software-school/bangazon-inc/blob/master/projects/WORKFORCE_MANAGEMENT.md) before filling out this section.

1. Add button to the razor view on the department listing page. 
2. On the department controller include an add method that will give the user an empty field for them to use.

### Related Issues/PRs
User Story #5

**Comment by matthamil** [comment]
Was this resolved by #52 @garrett-vangilder ?

**Comment by daynewright** [comment]
@garrett-vangilder  ☝️
