### ISSUE TITLE
Create Department Form

### ISSUE THREAD

**Issue by garrett-vangilder** [TeamCharles/workforce-management#28]
### Feature Description

Once the user has visited the department/add url they will view a form to add a new department to the database. Within this form there should be the following required fields. 

   - Department Name 
   - Department Description
   - Optional Select to include multiple employees to the department

### Recommended Actions
>Refer to the [project requirements](https://github.com/nashville-software-school/bangazon-inc/blob/master/projects/WORKFORCE_MANAGEMENT.md) before filling out this section.

1. Create a razor view that has all of the designated fields 
2. Grab all of employees from an employee list view model 
3. Populate a dropdown that can take multiple selects from the employee list.
4. Once all fields have been used then allow for the button to be activated, before then the button should be inactive. 

### Related Issues/PRs

User story #5

**Comment by matthamil** [comment]
Resolved with #50
