### ISSUE TITLE
Employee List Page Needs Full Name

### ISSUE THREAD

**Issue by daynewright** [TeamCharles/workforce-management#75]
### Feature Description
`/Employees` route needs to have full name.  Currently has first name only.

### Recommended Actions
>Refer to the [project requirements](https://github.com/nashville-software-school/bangazon-inc/blob/master/projects/WORKFORCE_MANAGEMENT.md) before filling out this section.

1.

**Comment by matthamil** [comment]
Repeat ticket https://github.com/TeamCharles/workforce-management/issues/66
